"""
Backend / API Engineer AI Fluency Builder
Creates a realistic Express API (10+ files) with controlled bugs:
- OpenAPI spec that doesn't match implementation
- SQL injection vulnerability
- Missing input validation
- Broken error handling
- Auth gaps
"""

import json
import logging
from typing import Dict, List, Any, Tuple

logger = logging.getLogger(__name__)


class BackendFluencyBuilder:
    """Builds Backend Engineer AI fluency simulation."""

    def build(self, role_id: str, difficulty: str = "medium", **kwargs) -> Dict[str, Any]:
        file_structure = self._get_base_template()
        bug_files, intentional_issues = self._inject_bugs(difficulty)
        file_structure.update(bug_files)
        file_structure["README.md"] = self._get_readme()

        return {
            "projectStructure": file_structure,
            "projectMetadata": {"role": role_id, "displayName": "Backend Engineer", "difficulty": difficulty, "estimatedMinutes": 45},
            "intentionalIssues": intentional_issues,
            "evaluationCriteria": {
                "security_awareness": "Did they find SQL injection and auth gaps?",
                "spec_compliance": "Did they notice the OpenAPI spec doesn't match the code?",
                "error_handling": "Did they add proper error responses?",
                "validation": "Did they add input validation?",
                "testing": "Did they write or fix tests?",
            },
            "candidateInstructions": (
                "This Express API was partially generated by AI. It has security holes, "
                "spec mismatches, and missing validation. Find and fix them. "
                "Run `npm install && npm start` to start. Use `npm test` to run tests."
            ),
            "setupInstructions": "npm install && npm start",
        }

    # ── Base template ──────────────────────────────────────────────

    def _get_base_template(self) -> Dict[str, str]:
        return {
            "package.json": json.dumps({
                "name": "backend-fluency-assessment",
                "version": "1.0.0",
                "private": True,
                "scripts": {
                    "start": "node src/server.js",
                    "dev": "node --watch src/server.js",
                    "test": "jest --forceExit",
                },
                "dependencies": {
                    "express": "^4.18.2",
                    "cors": "^2.8.5",
                    "helmet": "^7.1.0",
                    "better-sqlite3": "^9.4.3",
                    "express-rate-limit": "^7.1.4",
                },
                "devDependencies": {
                    "jest": "^29.7.0",
                    "supertest": "^6.3.3",
                },
            }, indent=2),
            # src/app.js — the express app (separated from server for testing)
            "src/app.js": (
                "const express = require('express');\n"
                "const cors = require('cors');\n"
                "const helmet = require('helmet');\n"
                "const taskRoutes = require('./routes/tasks');\n"
                "const userRoutes = require('./routes/users');\n"
                "const { errorHandler } = require('./middleware/errorHandler');\n\n"
                "const app = express();\n"
                "app.use(cors());\n"
                "app.use(helmet());\n"
                "app.use(express.json());\n\n"
                "app.use('/api/tasks', taskRoutes);\n"
                "app.use('/api/users', userRoutes);\n"
                "app.use(errorHandler);\n\n"
                "module.exports = app;\n"
            ),
            "src/server.js": (
                "const app = require('./app');\n"
                "const db = require('./db');\n\n"
                "const PORT = process.env.PORT || 3000;\n"
                "app.listen(PORT, () => console.log(`Server running on port ${PORT}`));\n"
            ),
            # db.js — SQLite setup
            "src/db.js": (
                "const Database = require('better-sqlite3');\n"
                "const path = require('path');\n\n"
                "const db = new Database(path.join(__dirname, '..', 'data.db'));\n\n"
                "db.exec(`\n"
                "  CREATE TABLE IF NOT EXISTS tasks (\n"
                "    id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                "    title TEXT NOT NULL,\n"
                "    description TEXT DEFAULT '',\n"
                "    status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'in_progress', 'done')),\n"
                "    priority INTEGER DEFAULT 0,\n"
                "    assignee TEXT,\n"
                "    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n"
                "    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n"
                "  );\n"
                "  CREATE TABLE IF NOT EXISTS users (\n"
                "    id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                "    username TEXT NOT NULL UNIQUE,\n"
                "    email TEXT NOT NULL UNIQUE,\n"
                "    role TEXT DEFAULT 'member' CHECK(role IN ('admin', 'member', 'viewer')),\n"
                "    created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n"
                "  );\n"
                "`);\n\n"
                "// Seed data\n"
                "const count = db.prepare('SELECT COUNT(*) as c FROM tasks').get();\n"
                "if (count.c === 0) {\n"
                "  const insert = db.prepare('INSERT INTO tasks (title, description, status, priority) VALUES (?, ?, ?, ?)');\n"
                "  insert.run('Setup CI pipeline', 'Configure GitHub Actions', 'pending', 2);\n"
                "  insert.run('Write unit tests', 'Add Jest test suite', 'in_progress', 3);\n"
                "  insert.run('Deploy to staging', 'Push v0.1 to staging env', 'done', 1);\n"
                "}\n\n"
                "module.exports = db;\n"
            ),
        }

    # ── Bug injection ──────────────────────────────────────────────

    def _inject_bugs(self, difficulty: str) -> Tuple[Dict[str, str], List[Dict[str, Any]]]:
        tier = {"easy": 3, "medium": 5, "hard": 7}.get(difficulty, 5)
        issues: List[Dict[str, Any]] = []
        files: Dict[str, str] = {}

        # ── routes/tasks.js — SQL injection + missing validation ──
        files["src/routes/tasks.js"] = (
            "// AI-generated: RESTful task routes with full validation\n"
            "const express = require('express');\n"
            "const router = express.Router();\n"
            "const db = require('../db');\n\n"
            "// GET /api/tasks — list all tasks\n"
            "router.get('/', (req, res) => {\n"
            "  const { status, sort } = req.query;\n"
            "  let sql = 'SELECT * FROM tasks';\n"
            "  if (status) {\n"
            "    sql += ` WHERE status = '${status}'`; // direct interpolation\n"
            "  }\n"
            "  if (sort) {\n"
            "    sql += ` ORDER BY ${sort}`; // direct interpolation\n"
            "  }\n"
            "  const tasks = db.prepare(sql).all();\n"
            "  res.json({ tasks });\n"
            "});\n\n"
            "// GET /api/tasks/:id\n"
            "router.get('/:id', (req, res) => {\n"
            "  const task = db.prepare('SELECT * FROM tasks WHERE id = ?').get(req.params.id);\n"
            "  res.json({ task }); // returns { task: undefined } instead of 404\n"
            "});\n\n"
            "// POST /api/tasks\n"
            "router.post('/', (req, res) => {\n"
            "  const { title, description, status, priority } = req.body;\n"
            "  // No input validation at all\n"
            "  const result = db.prepare(\n"
            "    'INSERT INTO tasks (title, description, status, priority) VALUES (?, ?, ?, ?)'\n"
            "  ).run(title, description || '', status || 'pending', priority || 0);\n"
            "  res.json({ id: result.lastInsertRowid, message: 'Task created' });\n"
            "});\n\n"
            "// PUT /api/tasks/:id\n"
            "router.put('/:id', (req, res) => {\n"
            "  const { title, description, status, priority } = req.body;\n"
            "  db.prepare(\n"
            "    'UPDATE tasks SET title = ?, description = ?, status = ?, priority = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'\n"
            "  ).run(title, description, status, priority, req.params.id);\n"
            "  res.json({ message: 'Task updated' }); // no check if task existed\n"
            "});\n\n"
            "// DELETE /api/tasks/:id\n"
            "router.delete('/:id', (req, res) => {\n"
            "  db.prepare('DELETE FROM tasks WHERE id = ?').run(req.params.id);\n"
            "  res.json({ message: 'Task deleted' }); // no check if task existed\n"
            "});\n\n"
            "module.exports = router;\n"
        )
        issues.append({"id": "bug_sql_injection", "description": "SQL injection via direct string interpolation in GET /api/tasks query params"})
        issues.append({"id": "bug_missing_validation", "description": "POST /api/tasks accepts any body — no title validation"})
        issues.append({"id": "bug_no_404", "description": "GET /api/tasks/:id returns 200 with undefined instead of 404"})

        # ── routes/users.js — auth bypass ──
        files["src/routes/users.js"] = (
            "// AI-generated: User management routes with role-based access control\n"
            "const express = require('express');\n"
            "const router = express.Router();\n"
            "const db = require('../db');\n\n"
            "// GET /api/users — anyone can list all users\n"
            "router.get('/', (req, res) => {\n"
            "  const users = db.prepare('SELECT * FROM users').all();\n"
            "  res.json({ users });\n"
            "});\n\n"
            "// DELETE /api/users/:id — anyone can delete any user\n"
            "router.delete('/:id', (req, res) => {\n"
            "  db.prepare('DELETE FROM users WHERE id = ?').run(req.params.id);\n"
            "  res.json({ message: 'User deleted' });\n"
            "});\n\n"
            "module.exports = router;\n"
        )
        issues.append({"id": "bug_auth_missing", "description": "DELETE /api/users/:id has no auth — anyone can delete any user"})

        # ── middleware/errorHandler.js — swallows errors ──
        files["src/middleware/errorHandler.js"] = (
            "// AI-generated: centralized error handler\n"
            "function errorHandler(err, req, res, next) {\n"
            "  console.log(err); // should be console.error\n"
            "  res.status(200).json({ error: 'Something went wrong' }); // always returns 200\n"
            "}\n\n"
            "module.exports = { errorHandler };\n"
        )
        issues.append({"id": "bug_error_handler_200", "description": "Error handler always returns 200 status — should return 500"})

        # ── OpenAPI spec that doesn't match ──
        files["openapi.yaml"] = (
            "openapi: 3.0.3\n"
            "info:\n"
            "  title: Task API\n"
            "  version: 1.0.0\n"
            "paths:\n"
            "  /api/tasks:\n"
            "    get:\n"
            "      summary: List tasks\n"
            "      parameters:\n"
            "        - name: status\n"
            "          in: query\n"
            "          schema:\n"
            "            type: string\n"
            "            enum: [pending, in_progress, done, archived]\n"
            "      responses:\n"
            "        '200':\n"
            "          description: Array of tasks\n"
            "          content:\n"
            "            application/json:\n"
            "              schema:\n"
            "                type: object\n"
            "                properties:\n"
            "                  tasks:\n"
            "                    type: array\n"
            "                    items:\n"
            "                      $ref: '#/components/schemas/Task'\n"
            "                  total:\n"
            "                    type: integer\n"
            "    post:\n"
            "      summary: Create task\n"
            "      requestBody:\n"
            "        required: true\n"
            "        content:\n"
            "          application/json:\n"
            "            schema:\n"
            "              type: object\n"
            "              required: [title]\n"
            "              properties:\n"
            "                title:\n"
            "                  type: string\n"
            "                  minLength: 1\n"
            "                  maxLength: 200\n"
            "                description:\n"
            "                  type: string\n"
            "                priority:\n"
            "                  type: integer\n"
            "                  minimum: 0\n"
            "                  maximum: 5\n"
            "      responses:\n"
            "        '201':\n"
            "          description: Task created\n"
            "        '400':\n"
            "          description: Validation error\n"
            "components:\n"
            "  schemas:\n"
            "    Task:\n"
            "      type: object\n"
            "      properties:\n"
            "        id:\n"
            "          type: integer\n"
            "        title:\n"
            "          type: string\n"
            "        description:\n"
            "          type: string\n"
            "        status:\n"
            "          type: string\n"
            "          enum: [pending, in_progress, done, archived]\n"
            "        priority:\n"
            "          type: integer\n"
        )
        issues.append({"id": "bug_spec_mismatch", "description": "OpenAPI spec says 'archived' status and 'total' field exist but DB/code don't support them"})

        if tier >= 5:
            # ── middleware/auth.js exists but is never used ──
            files["src/middleware/auth.js"] = (
                "// AI-generated: authentication middleware\n"
                "function authenticate(req, res, next) {\n"
                "  const token = req.headers.authorization;\n"
                "  if (!token) {\n"
                "    return res.status(401).json({ error: 'Unauthorized' });\n"
                "  }\n"
                "  // TODO: validate token\n"
                "  req.user = { id: 1, role: 'admin' }; // hardcoded\n"
                "  next();\n"
                "}\n\n"
                "function requireRole(role) {\n"
                "  return (req, res, next) => {\n"
                "    if (req.user && req.user.role === role) {\n"
                "      return next();\n"
                "    }\n"
                "    return res.status(403).json({ error: 'Forbidden' });\n"
                "  };\n"
                "}\n\n"
                "module.exports = { authenticate, requireRole };\n"
            )
            issues.append({"id": "bug_auth_not_wired", "description": "Auth middleware exists but is never used in any route"})

        if tier >= 6:
            # ── response code mismatch ──
            issues.append({"id": "bug_post_returns_200", "description": "POST /api/tasks returns 200 instead of 201 for creation"})

        if tier >= 7:
            # ── no rate limiting on write endpoints ──
            issues.append({"id": "bug_no_rate_limit", "description": "No rate limiting on POST/PUT/DELETE — vulnerable to abuse"})

        # ── Tests — mix of passing and failing ──
        files["test/tasks.test.js"] = (
            "const request = require('supertest');\n"
            "const app = require('../src/app');\n\n"
            "describe('Task API', () => {\n"
            "  test('GET /api/tasks returns list', async () => {\n"
            "    const res = await request(app).get('/api/tasks');\n"
            "    expect(res.status).toBe(200);\n"
            "    expect(res.body.tasks).toBeDefined();\n"
            "  });\n\n"
            "  test('POST /api/tasks creates task', async () => {\n"
            "    const res = await request(app)\n"
            "      .post('/api/tasks')\n"
            "      .send({ title: 'Test task' });\n"
            "    expect(res.status).toBe(201); // will FAIL — code returns 200\n"
            "  });\n\n"
            "  test('POST /api/tasks rejects empty title', async () => {\n"
            "    const res = await request(app)\n"
            "      .post('/api/tasks')\n"
            "      .send({});\n"
            "    expect(res.status).toBe(400); // will FAIL — no validation\n"
            "  });\n\n"
            "  test('GET /api/tasks/:id returns 404 for non-existent', async () => {\n"
            "    const res = await request(app).get('/api/tasks/99999');\n"
            "    expect(res.status).toBe(404); // will FAIL — returns 200\n"
            "  });\n\n"
            "  test('error handler returns 500', async () => {\n"
            "    // Intentionally trigger an error\n"
            "    const res = await request(app).get('/api/nonexistent');\n"
            "    // At least should not be 200 for errors\n"
            "    expect(res.status).not.toBe(200);\n"
            "  });\n"
            "});\n"
        )

        files["test/security.test.js"] = (
            "const request = require('supertest');\n"
            "const app = require('../src/app');\n\n"
            "describe('Security', () => {\n"
            "  test('SQL injection in status filter should be prevented', async () => {\n"
            "    const res = await request(app).get(\"/api/tasks?status=pending' OR '1'='1\");\n"
            "    // Should not return all tasks\n"
            "    expect(res.status).toBe(200);\n"
            "  });\n\n"
            "  test('DELETE /api/users should require auth', async () => {\n"
            "    const res = await request(app).delete('/api/users/1');\n"
            "    expect(res.status).toBe(401); // will FAIL — no auth\n"
            "  });\n"
            "});\n"
        )

        return files, issues

    # ── README ─────────────────────────────────────────────────────

    def _get_readme(self) -> str:
        return """# Backend AI Fluency Assessment

## Scenario
You inherited an Express API that was scaffolded using AI. The team needs you to review
and fix it before it goes to production. There's an OpenAPI spec in `openapi.yaml` that
describes what the API *should* do.

## Instructions
1. **Run the app** — `npm install && npm start` (runs on port 3000)
2. **Run tests** — `npm test` (several tests fail — figure out why)
3. **Compare spec vs code** — Does the implementation match `openapi.yaml`?
4. **Find security issues** — Check for injection, auth gaps, error handling
5. **Fix everything** — Make tests pass, close security holes, match the spec

## What we're measuring
- Do you catch SQL injection vulnerabilities?
- Do you notice the spec doesn't match the implementation?
- Do you add proper input validation?
- Do you fix error handling (status codes, error responses)?
- Do you wire up the existing auth middleware?
- Do you verify fixes with tests?

Good luck.
"""
